name: Smelter
main: com.spoljo.smelter.main.Main
version: 1.3.1
depend: [Vault]
authors:
 - spoljo666spoljo
 - instancelabs
description: Smelt items using commands.
commands:
  smelt:
    description: Smelts your items from your hand.
    usage: /smelt
permissions:
  smelter.use.smelt:
    Description: Allows the use of the /smelt command.
    default: op
  smelter.bypasscooldown:
    Description: Allows to bypass the cooldown on the /smelt commands.
    default: op
